version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql_host
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306:3306